spring:
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
    password: 123
    username: postgres
    url: jdbc:postgresql://localhost:5432/math?useSSL=false
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
